# Generated by Django 6.0.1 on 2026-01-10 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medication_name", models.CharField(max_length=200)),
                ("order_date", models.DateField()),
                ("additional_diagnoses", models.JSONField(blank=True, default=list)),
                ("medication_history", models.JSONField(blank=True, default=list)),
                ("patient_records_text", models.TextField()),
                ("duplicate_warning", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        help_text="Unique 6-digit medical record number.",
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="MRN must be exactly 6 digits.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "primary_diagnosis_icd10",
                    models.CharField(
                        help_text="Primary ICD-10 code (format validation can be added later).",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "npi",
                    models.CharField(
                        help_text="10-digit National Provider Identifier.",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="NPI must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="CarePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_text", models.TextField()),
                ("llm_model", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_plan",
                        to="careplans.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="careplans.patient",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="careplans.provider",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("patient", "medication_name", "order_date"),
                name="uniq_order_patient_med_date",
            ),
        ),
    ]
