# Generated by Django 6.0.1 on 2026-01-10 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careplans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="uniq_order_patient_med_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="duplicate_warning",
            new_name="is_possible_duplicate_order",
        ),
        migrations.RemoveField(
            model_name="careplan",
            name="llm_model",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="primary_diagnosis_icd10",
        ),
        migrations.AddField(
            model_name="order",
            name="duplicate_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="primary_diagnosis_icd10",
            field=models.CharField(default="PENDING", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="additional_diagnoses",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="medication_history",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(help_text="The actual date the order was placed."),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6,8}$", "MRN must be between 6 and 8 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="npi",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "NPI must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("patient", "medication_name", "order_date"),
                name="unique_order_constraint",
            ),
        ),
    ]
