# Generated by Django 6.0.1 on 2026-01-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careplans", "0002_remove_order_uniq_order_patient_med_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
