# Generated by Django 6.0.1 on 2026-01-11 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careplans", "0003_patient_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="additional_diagnoses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="medication_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="primary_diagnosis_icd10",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-TV-Z][0-9][A-Z0-9](\\.[A-Z0-9]{1,4})?$",
                        "Invalid ICD-10 format.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "MRN must be exactly 6 digits."
                    )
                ],
            ),
        ),
    ]
